### ISSUE TITLE
Bluetooth mode

### ISSUE THREAD

**Issue by SiddTheWusky** [ilker-aktuna/Gear-360-File-Access-from-Android-phones#3]
After installing the V2 folder the Bluetooth mode is no longer working

**Comment by ilker-aktuna** [comment]
you have to remove all installed  files on SD then install V2 folder and power off/power on.

**Comment by SiddTheWusky** [comment]
I tried that and it still would not reconnect to Bluetooth

**Comment by SiddTheWusky** [comment]
the only way I could get the gear 360 app to find the camera again was to delete the mod files from the SD card

**Comment by ilker-aktuna** [comment]
that's interesting. If you do not activate web server on the Gear360 , BT mode should work.
On V2 files, you can do that by NOT starting web server after power on.
Of course, you have to switch to "android" mode on camera.

**Comment by SiddTheWusky** [comment]
As soon as I boot it up the light on top flashes orange and then green and then orange again even tho I am using the v2 version, it's as tho the web server is immediately starting upon boot

**Comment by ilker-aktuna** [comment]
well, the difference between V2 and V1 is the mod.sh file.
on V1 it blinks the led (no5) and starts web server.
then stops blink.
on V2 it also blinks the led (no 5) but instead of starting web server puts a trigger to the power button double click.
so when power button is clicked twice it starts web server.

this is done by the G360POWE_G360POW.sh file

Please make sure you remove everything from V1 on your SD card.
run and see that web server is not activated.
Then you just install V2 folder. in this state web server does not start if you don't double click power button.

**Comment by intelmation** [comment]
This is still a bug, I can confirm.

If I format an SD card and insert, I can connect via BT using the old Samsung App.
If I then install the File Manager V2 files, I cam locked out of the Samsung app.

**Comment by ilker-aktuna** [comment]
well, that's a problem of the mod I think.
but for some , the V2 files had solved the issue by not starting the http server.
did you try without ever starting the http server ?
