### ISSUE TITLE
No file access

### ISSUE THREAD

**Issue by johnawalkeruk** [ilker-aktuna/Gear-360-File-Access-from-Android-phones#5]
Connected to the camera. It give me the option to shoot by I have no access to the files that are on it? If you can provide a support email I will send a screenshot

**Comment by ilker-aktuna** [comment]
actually there is a developer contact on Google Play store:
![image](https://github.com/ilker-aktuna/Gear-360-File-Access-from-Android-phones/assets/51407106/acc3d8fa-dd5b-4e6e-bd69-6873a843b205)

and:

![image](https://github.com/ilker-aktuna/Gear-360-File-Access-from-Android-phones/assets/51407106/1974b870-9f56-486f-88c5-dce8a2fd34f1)


but you can also post the screenshot here.
it would be even better.

**Comment by JamshidCT** [comment]
Hello Ilker,

I wanted to firstly thank you, The code works perfectly,

wanted to flag this same issue, the app works but I'm faced with this one screen, it allows me to remote shoot, but not really access the file, I can't seem to find any menus there,

![image](https://github.com/ilker-aktuna/Gear-360-File-Access-from-Android-phones/assets/76052514/fcf39639-9b4c-4d97-93a1-2e8759a6043a)


Not sure where the issue is coming from, I did notice the gear360 did not make the system folder,

I am using s S21 Ultra with a Gear 360 2017.

Many thanks,

**Comment by ilker-aktuna** [comment]
Did you Read the instructions correctly ?
You have to prepare your SD card exactly as I wrote in the instructions. The folder should be in the root of your SD card.
And then you have to follow the instructions from the app.
If you follow but fails, then please :
1.	Uninstall app
2.	record a screen video while you reinstall and setup
3.	Try again ,if fails send video to me.

**Comment by josegzuritac** [comment]
Hi, Ilker. First of all, thank you so much for working on this project.
I have the same problem and, as you requested, I recorded a video.
I tried the v2 at first, and since I can't see the files, I tried the v1 too. The video is with the v1 version.
My phone is a Samsung S20 FE with Android 13.


I hope it helps you to find the issue. Let me know if you need more information. I'll be glad to help.

https://github.com/ilker-aktuna/Gear-360-File-Access-from-Android-phones/assets/155648705/f66dadd5-4d86-4045-80cc-6e1d96fccdfa

**Comment by ilker-aktuna** [comment]
@josegzuritac 
thanks for sharing that video.
So you connect the camera but you only see the "shoot" button and no "browse" button.
That is interesting. What is the pjhone you are running this on ?
The fonts are too small. Do you have a special screen setting ? Scaled fonts etc ?
is it a large screen tablet ?

**Comment by ilker-aktuna** [comment]
@josegzuritac 
I've just checked my code and see when the "shoot" button is active and "browse" is not active.
The app checks 2 URLs on the camera:
1. http://192.168.43.1:8888   ---> this is for the "browse" function
2. http://192.168.43.1/osc/commands/execute ---> this is for the "shoot" function
In your setup, since you don't see the "browse" button, probably the custom web server (from this github project) is not running.
You either don't have the files correctly copied to the camera (they should be in the root directory of the SD card) or you do not start the web server.
Please check the following important note on the project:

important:
if you want to use the BT mode occasionally, please try the version 2 of the folder. (SD-card-root-V2) this version does not start the httpd server automatically when powered-on. instead, user has to Double-click the [Power] button on the camera. Then user should see a top light cycle green-orange-green to indicate it's working. this is for users who still want to use the BT mode when required. Because if httpd server is running , BT mode does not work.

**Comment by josegzuritac** [comment]
Hi again!
Thank you for the response and for still supporing this camera!
My phone is a Samsung s20 fe 5g and yes, it's on the smaller screen setting, and set on 587 dpi.

I really think I did everything correctly. As I knew v2 could be a problem due to the server, I already replaced it with the first version, but the issue is still there. :(

Maybe it's not going to the right url. (I don't know about this, so sorry if it doesn't make sense). Is there a way to see which url is the server on my camera?

**Comment by ilker-aktuna** [comment]
well, you can try connecting to the camera wifi from a PC and then try these URLs:
http://192.168.43.1:8888/ ---> this is for the "browse" function
http://192.168.43.1/osc/commands/execute ---> this is for the "shoot" function

**Comment by josegzuritac** [comment]
> well, you can try connecting to the camera wifi from a PC and then try these URLs: http://192.168.43.1:8888/ ---> this is for the "browse" function http://192.168.43.1/osc/commands/execute ---> this is for the "shoot" function

Not working either. :(

I don't want to bother you, so don't feel obligated to fix this, but if you want to, I'm here to help. :) Just tell me what to do.
![Captura de pantalla 2024-02-25 135949](https://github.com/ilker-aktuna/Gear-360-File-Access-from-Android-phones/assets/155648705/b1c8cd9d-1240-488b-bde1-e2f514622af5)
![Captura de pantalla 2024-02-25 135805](https://github.com/ilker-aktuna/Gear-360-File-Access-from-Android-phones/assets/155648705/ca98454f-1996-4305-b53b-f01b9ae2eb1c)

**Comment by ilker-aktuna** [comment]
well , actually I want to solve this issue but I don't understand what's wrong.
OK. Let's start from scratch:
1. Please send me a photo of your camera (Gear 360)  - I want to make sure it is a supported model
2. Please sendme also a photo of your camera screen when streetview / OSC option is selected
3. Please send a screenshot from your phone where Gear 360 camera network is selected (wifi settings)
4. Please send a screenshow from your PC showing the root folder of the SD card.
I'm sure we'll find where the mistake is with these 4 photos/screenshots

**Comment by JamshidCT** [comment]
Hello again,

Just wanting to thank you again,

I managed to get it working,

The issue stemed from the app, and SD card, I redid the steps and reinstalled the app, and additionally I made sure to reformat the sd card multiple times after each try,

I believe I used root V1 and it worked.

The network you use does have an impact as well.

So hope that helps identify the problem!

**Comment by ilker-aktuna** [comment]
I didn't understand. Did you reinstall SD card content and it started working ?
If that's the case, we can say there is no issue. So what do we have to identify ?

**Comment by JamshidCT** [comment]
It was more the app needed to be reinstalled, and there was network security prevnting it.
  

  
I just had to redo every step until it worked.
  

  

  
  
  
  
  
Keeping it sweet,
  
 Jamshid (Chaikar) Tavallali     
  
University Student / Entrepreneur / Published Author/ Consultant/ Jam of all trades
  
  
  
United Kingdom
  
  
  
  
  
  
  
Book a meeting
 Mobile:   +447474929099     
  
Work:   ***@***.***
  
  
  
  
  
  
  
  
  
  Save My Contact
  
  
  
  
  
  
  
  
  
>

**Comment by ilker-aktuna** [comment]
I am not sure what was wrong on your previous installation. But it seems like a missing permission.
Please let me know if you have any other insight. With the limited information I am not able to comment on it.

**Comment by josegzuritac** [comment]
Hi again, ilker!

It finally works! I just needed to format the sd card, place the files and then insert it into the gear360.

Thanks to JamshidCT for the tip. :)

It's on xfat with deep format, but it's what worked for me at the first attempt, so not sure if ntsc will or will not work. 

Thanks again, ilker, for all your support. You're great!

![Screenshot_20240330_093001_Gear 360 File Access](https://github.com/ilker-aktuna/Gear-360-File-Access-from-Android-phones/assets/155648705/c630fba0-94ea-44b3-96f1-5779bfdb9e06)
![Screenshot_20240330_093021_Gear 360 File Access](https://github.com/ilker-aktuna/Gear-360-File-Access-from-Android-phones/assets/155648705/c0fbeb43-079d-4074-8209-cf9ceec6068d)

**Comment by ilker-aktuna** [comment]
thanks for the feedback
